// import './vendor.js';
import './popup-payment.js';
import './popup-work.js';
import './popup-confidentiality.js';
import './popup-conditions.js';
import './popup-congratulation.js';
import './popup-cookie.js';
import './popup-cookie-info.js';
import './popup-app.js';
import './popup-category.js';
import './popup-compare.js';
import './popup-promotion.js';
import './search.js';
import './swipers.js';
